### ISSUE TITLE
Do a five minute talk introducing Codespaces at the Tuesday all hands meeting

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#29]

**Comment by StevenMaude** [comment]
I've done this previously a couple of times last year, showing what Codespaces is and how it works.

But I think it would still be good to run through again — because sometimes you need to see an idea a couple of times before you make sense of it.

That could also be with introduction of the *why*, more than the *what* — why we propose that Codespaces could be useful. We currently think that:

* Primarily, **Codespaces makes it easier for *OpenSAFELY users* to write code.**
  * It removes the need for a local development setup, at least in the initial stages of a project. This simplifies getting started, because of not needing IT administrators involved, and because of fewer steps.
* **Codespaces makes it easier for *others* to try out or help work on that code.** The ideal scenario would be a single web site button that lets you work on a project, perhaps from within job-server.
  * It gives a route for others associated with the project or OpenSAFELY, like project copilots, to more quickly debug your project.
  * It gives a route for collaboration with Live Share.
  * It gives a route for others external to the project — peer reviewers, other researchers, interested members of the public — to run OpenSAFELY code, albeit without access to real data. That's in line with some of Bennett Institute's goals for open and reproducible scientific research code.

We should also mention, as Iain points out, that because the code's in a Git repository, **users can always switch to a local setup at any time**. And that local setup could look a lot like Codespaces, if we use Visual Studio Code running a dev container.

**Comment by lucyb** [comment]
Thanks Steve. I had forgotten that you'd run through Codespaces with the whole group last year. Given that, I think it would be worth holding off on this until we have something more concrete to show to people, otherwise we risk just demonstrating what's already there and people might miss the very important points that you mention.

**Comment by lucyb** [comment]
I'm happy to give a five minute talk about why we're doing this initiative and where we're up to at the next All Hands meeting. However, I think the next free slot will be after Easter.

EDIT: I've booked in a slot on the 9th April.
